import { useCallback, useEffect, useState } from "react";

type Station = "MAITRI" | "BHARATI";

interface SimulationImpact {
  [key: string]: unknown;
}

interface ScenarioEntity {
  id: number;
  station?: {
    code?: string;
  };
  scenarioName?: string;
  description?: string;
  horizonHours?: number;
}

interface SimulationResult {
  station: string;
  scenarioName: string;
  horizonHours: number;
  baselineState: Record<string, unknown>;
  simulatedState: Record<string, unknown>;
  impact: SimulationImpact;
}

interface DecisionResult {
  decisionCode: string;
  decision: string;
  riskScore: number;
  riskLevel: string;
  primaryRisk: string;
  reason: string;
}

interface ActionRecommendation {
  actionCode: string;
  action: string;
  priority: string;
  reason: string;
}

interface RecommendationResult {
  decisionCode: string;
  decision: string;
  riskLevel: string;
  riskScore: number;
  primaryRisk: string;
  recommendations: ActionRecommendation[];
}

interface ExplanationResult {
  summary: string;
  detailedExplanation: string;
  operationalImplication: string;
  primaryRisk: string;
  riskLevel: string;
  riskScore: number;
  decisionCode: string;
  decision: string;
  impactFactors: string[];
  recommendationCount: number;
}

interface DecisionProps {
  station: Station;
}

const riskStyles: Record<
  string,
  {
    color: string;
    background: string;
    border: string;
  }
> = {
  LOW: {
    color: "#10b981",
    background: "rgba(16,185,129,0.08)",
    border: "rgba(16,185,129,0.25)",
  },
  MEDIUM: {
    color: "#f59e0b",
    background: "rgba(245,158,11,0.08)",
    border: "rgba(245,158,11,0.25)",
  },
  HIGH: {
    color: "#f97316",
    background: "rgba(249,115,22,0.08)",
    border: "rgba(249,115,22,0.25)",
  },
  CRITICAL: {
    color: "#ef4444",
    background: "rgba(239,68,68,0.08)",
    border: "rgba(239,68,68,0.25)",
  },
};

function riskStyle(level: string) {
  return (
    riskStyles[level?.toUpperCase()] ?? {
      color: "#94a3b8",
      background: "rgba(148,163,184,0.06)",
      border: "rgba(148,163,184,0.18)",
    }
  );
}

function formatNumber(value: unknown, decimals = 2) {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return "—";
  }

  return value.toLocaleString("en-IN", {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

function formatLabel(value: string) {
  return value
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/_/g, " ")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function impactEntries(impact: SimulationImpact | null) {
  if (!impact) return [];

  return Object.entries(impact)
    .filter(
      ([, value]) =>
        value !== null &&
        value !== undefined &&
        typeof value !== "object",
    )
    .map(([key, value]) => ({
      label: formatLabel(key),
      value:
        typeof value === "number"
          ? formatNumber(value)
          : String(value),
    }));
}

export default function Decision({ station }: DecisionProps) {
  const [scenario, setScenario] =
    useState<ScenarioEntity | null>(null);

  const [simulation, setSimulation] =
    useState<SimulationResult | null>(null);

  const [decision, setDecision] =
    useState<DecisionResult | null>(null);

  const [recommendations, setRecommendations] =
    useState<RecommendationResult | null>(null);

  const [explanation, setExplanation] =
    useState<ExplanationResult | null>(null);

  const [loading, setLoading] =
    useState(false);

  const [error, setError] =
    useState("");

  const loadDecision = useCallback(async () => {
    if (loading) return;

    setLoading(true);
    setError("");

    try {
      /*
       * Get scenarios belonging to the currently selected station.
       * The backend stores the scenario created by the Simulation UI.
       */
      const scenarioResponse = await fetch(
        `/api/simulation/scenarios/station/${station}`,
      );

      if (!scenarioResponse.ok) {
        const message = await scenarioResponse.text();

        throw new Error(
          `Unable to load ${station} scenarios (${scenarioResponse.status})${
            message ? `: ${message}` : ""
          }`,
        );
      }

      const scenarioData =
        (await scenarioResponse.json()) as ScenarioEntity[];

      if (!Array.isArray(scenarioData) || scenarioData.length === 0) {
        throw new Error(
          `No saved simulation scenarios were found for ${station}. Run a simulation first.`,
        );
      }

      /*
       * The API returns saved scenarios. We use the newest scenario
       * by numeric ID because scenario IDs are generated by the backend.
       */
      const latestScenario = [...scenarioData].sort(
        (a, b) => b.id - a.id,
      )[0];

      setScenario(latestScenario);

      /*
       * Re-run the saved scenario to obtain a fresh SimulationImpact.
       * This guarantees the decision engine receives the exact backend
       * simulation contract rather than frontend-generated values.
       */
      const runResponse = await fetch(
        `/api/simulation/scenarios/${latestScenario.id}/run`,
        {
          method: "POST",
        },
      );

      if (!runResponse.ok) {
        const message = await runResponse.text();

        throw new Error(
          `Simulation execution failed (${runResponse.status})${
            message ? `: ${message}` : ""
          }`,
        );
      }

      const simulationResult =
        (await runResponse.json()) as SimulationResult;

      if (!simulationResult.impact) {
        throw new Error(
          "Simulation completed without a SimulationImpact.",
        );
      }

      setSimulation(simulationResult);

      /*
       * Decision Engine
       */
      const decisionResponse = await fetch(
        "/api/simulation/decision",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(
            simulationResult.impact,
          ),
        },
      );

      if (!decisionResponse.ok) {
        const message = await decisionResponse.text();

        throw new Error(
          `Decision engine failed (${decisionResponse.status})${
            message ? `: ${message}` : ""
          }`,
        );
      }

      const decisionResult =
        (await decisionResponse.json()) as DecisionResult;

      setDecision(decisionResult);

      /*
       * Action Recommendation Engine
       */
      const recommendationResponse = await fetch(
        "/api/simulation/recommendations",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(
            simulationResult.impact,
          ),
        },
      );

      if (!recommendationResponse.ok) {
        const message =
          await recommendationResponse.text();

        throw new Error(
          `Recommendation engine failed (${recommendationResponse.status})${
            message ? `: ${message}` : ""
          }`,
        );
      }

      const recommendationResult =
        (await recommendationResponse.json()) as RecommendationResult;

      setRecommendations(recommendationResult);

      /*
       * Decision Explanation Engine
       */
      const explanationResponse = await fetch(
        "/api/simulation/explanation",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(
            simulationResult.impact,
          ),
        },
      );

      if (!explanationResponse.ok) {
        const message =
          await explanationResponse.text();

        throw new Error(
          `Explanation engine failed (${explanationResponse.status})${
            message ? `: ${message}` : ""
          }`,
        );
      }

      const explanationResult =
        (await explanationResponse.json()) as ExplanationResult;

      setExplanation(explanationResult);
    } catch (err) {
      console.error(
        "ANTARIS decision integration error:",
        err,
      );

      setError(
        err instanceof Error
          ? err.message
          : "Unable to generate operational decision.",
      );

      setScenario(null);
      setSimulation(null);
      setDecision(null);
      setRecommendations(null);
      setExplanation(null);
    } finally {
      setLoading(false);
    }
  }, [station, loading]);

  useEffect(() => {
    setScenario(null);
    setSimulation(null);
    setDecision(null);
    setRecommendations(null);
    setExplanation(null);
    setError("");
  }, [station]);

  const risk = riskStyle(
    decision?.riskLevel ??
      recommendations?.riskLevel ??
      explanation?.riskLevel ??
      "",
  );

  const impact = impactEntries(
    simulation?.impact ?? null,
  );

  return (
    <div
      style={{
        padding: "20px",
        display: "flex",
        flexDirection: "column",
        gap: 14,
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          gap: 16,
        }}
      >
        <div>
          <div
            className="font-mono"
            style={{
              fontSize: 9,
              color: "#00c8e8",
              letterSpacing: "0.14em",
              marginBottom: 5,
            }}
          >
            SIMULATE / DECIDE
          </div>

          <h1
            className="font-display"
            style={{
              margin: 0,
              fontSize: 24,
              fontWeight: 700,
              letterSpacing: "0.06em",
              color: "#e2e8f0",
            }}
          >
            DECISION & RECOMMENDATIONS
          </h1>

          <p
            style={{
              margin: "6px 0 0",
              fontSize: 13,
              color: "#64748b",
            }}
          >
            Convert simulated operational impact into
            explainable decisions and recommended actions.
          </p>
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "flex-end",
            gap: 4,
          }}
        >
          <div
            className="font-mono"
            style={{
              fontSize: 8,
              color: "#475569",
              letterSpacing: "0.12em",
            }}
          >
            ACTIVE STATION
          </div>

          <div
            className="font-display"
            style={{
              fontSize: 15,
              fontWeight: 700,
              color: "#00c8e8",
            }}
          >
            {station}
          </div>

          {scenario && (
            <div
              className="font-mono"
              style={{
                fontSize: 8,
                color: "#475569",
              }}
            >
              SCENARIO #{scenario.id}
            </div>
          )}
        </div>
      </div>

      {error && (
        <div
          style={{
            padding: "11px 13px",
            borderRadius: 6,
            border:
              "1px solid rgba(239,68,68,0.25)",
            background:
              "rgba(239,68,68,0.06)",
            color: "#fca5a5",
            fontSize: 11,
            fontFamily: "JetBrains Mono",
          }}
        >
          DECISION ERROR · {error}
        </div>
      )}

      <div
        className="glass-strong"
        style={{
          padding: 16,
          borderRadius: 8,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          gap: 14,
          flexWrap: "wrap",
        }}
      >
        <div>
          <div
            className="font-mono"
            style={{
              fontSize: 8,
              color: "#475569",
              letterSpacing: "0.12em",
            }}
          >
            DECISION ENGINE INPUT
          </div>

          <div
            style={{
              marginTop: 5,
              color: "#94a3b8",
              fontSize: 12,
            }}
          >
            Latest saved {station} simulation impact
          </div>
        </div>

        <button
          className="btn-primary"
          onClick={loadDecision}
          disabled={loading}
          style={{
            minWidth: 190,
            padding: "11px 16px",
            fontSize: 11,
            letterSpacing: "0.08em",
          }}
        >
          {loading
            ? "EVALUATING..."
            : "GENERATE DECISION"}
        </button>
      </div>

      {!decision && !loading && !error && (
        <div
          className="glass"
          style={{
            borderRadius: 8,
            padding: 48,
            textAlign: "center",
          }}
        >
          <div
            className="font-display"
            style={{
              fontSize: 15,
              color: "#475569",
              letterSpacing: "0.06em",
            }}
          >
            DECISION ENGINE READY
          </div>

          <p
            style={{
              margin: "7px auto 0",
              maxWidth: 480,
              color: "#334155",
              fontSize: 11,
            }}
          >
            Run a simulation first, then generate the
            operational decision from its real backend
            SimulationImpact.
          </p>
        </div>
      )}

      {loading && (
        <div
          className="glass"
          style={{
            borderRadius: 8,
            padding: 45,
            textAlign: "center",
          }}
        >
          <div
            style={{
              width: 30,
              height: 30,
              margin: "0 auto 14px",
              border:
                "2px solid rgba(0,200,232,0.15)",
              borderTopColor: "#00c8e8",
              borderRadius: "50%",
              animation:
                "decision-spin 0.8s linear infinite",
            }}
          />

          <div
            className="font-mono"
            style={{
              fontSize: 9,
              color: "#00c8e8",
              letterSpacing: "0.12em",
            }}
          >
            RUNNING DECISION PIPELINE
          </div>

          <div
            style={{
              marginTop: 7,
              fontSize: 11,
              color: "#475569",
            }}
          >
            Simulation → Risk → Decision →
            Recommendations → Explanation
          </div>

          <style>{`
            @keyframes decision-spin {
              to {
                transform: rotate(360deg);
              }
            }
          `}</style>
        </div>
      )}

      {decision && (
        <>
          <div
            style={{
              display: "grid",
              gridTemplateColumns:
                "minmax(0, 1.5fr) repeat(3, minmax(130px, 1fr))",
              gap: 10,
            }}
          >
            <div
              style={{
                padding: 18,
                borderRadius: 8,
                background: risk.background,
                border: `1px solid ${risk.border}`,
              }}
            >
              <div
                className="font-mono"
                style={{
                  fontSize: 8,
                  color: risk.color,
                  letterSpacing: "0.12em",
                  marginBottom: 7,
                }}
              >
                OPERATIONAL DECISION
              </div>

              <div
                className="font-display"
                style={{
                  fontSize: 18,
                  fontWeight: 700,
                  color: "#e2e8f0",
                }}
              >
                {decision.decisionCode}
              </div>

              <div
                style={{
                  marginTop: 7,
                  fontSize: 11,
                  color: "#94a3b8",
                  lineHeight: 1.5,
                }}
              >
                {decision.decision}
              </div>
            </div>

            <MetricCard
              label="RISK SCORE"
              value={formatNumber(
                decision.riskScore,
                2,
              )}
              valueColor={risk.color}
            />

            <MetricCard
              label="RISK LEVEL"
              value={decision.riskLevel}
              valueColor={risk.color}
            />

            <MetricCard
              label="PRIMARY RISK"
              value={decision.primaryRisk}
              valueColor="#00c8e8"
            />
          </div>

          <div
            className="glass"
            style={{
              borderRadius: 8,
              padding: 18,
            }}
          >
            <div
              className="section-label"
              style={{
                marginBottom: 10,
              }}
            >
              DECISION BASIS
            </div>

            <div
              style={{
                color: "#94a3b8",
                fontSize: 12,
                lineHeight: 1.65,
              }}
            >
              {decision.reason}
            </div>
          </div>

          {recommendations && (
            <div
              className="glass"
              style={{
                borderRadius: 8,
                padding: 18,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginBottom: 14,
                }}
              >
                <div className="section-label">
                  ACTION RECOMMENDATIONS
                </div>

                <div
                  className="font-mono"
                  style={{
                    fontSize: 8,
                    color: "#475569",
                  }}
                >
                  {recommendations.recommendations.length} ACTIONS
                </div>
              </div>

              <div
                style={{
                  display: "flex",
                  flexDirection: "column",
                  gap: 9,
                }}
              >
                {recommendations.recommendations.map(
                  (item, index) => {
                    const priority = riskStyle(
                      item.priority,
                    );

                    return (
                      <div
                        key={`${item.actionCode}-${index}`}
                        style={{
                          display: "grid",
                          gridTemplateColumns:
                            "28px 1fr auto",
                          gap: 11,
                          alignItems: "start",
                          padding: 12,
                          borderRadius: 6,
                          background:
                            "rgba(148,163,184,0.025)",
                          border:
                            "1px solid rgba(148,163,184,0.08)",
                        }}
                      >
                        <div
                          className="font-mono"
                          style={{
                            width: 25,
                            height: 25,
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                            borderRadius: 4,
                            background:
                              "rgba(0,200,232,0.08)",
                            color: "#00c8e8",
                            fontSize: 10,
                            fontWeight: 700,
                          }}
                        >
                          {index + 1}
                        </div>

                        <div>
                          <div
                            className="font-display"
                            style={{
                              color: "#e2e8f0",
                              fontSize: 13,
                              fontWeight: 700,
                            }}
                          >
                            {item.action}
                          </div>

                          <div
                            style={{
                              marginTop: 4,
                              color: "#64748b",
                              fontSize: 10,
                              lineHeight: 1.5,
                            }}
                          >
                            {item.reason}
                          </div>

                          <div
                            className="font-mono"
                            style={{
                              marginTop: 5,
                              fontSize: 8,
                              color: "#475569",
                            }}
                          >
                            {item.actionCode}
                          </div>
                        </div>

                        <span
                          className="font-mono"
                          style={{
                            padding: "4px 7px",
                            borderRadius: 3,
                            color: priority.color,
                            background:
                              priority.background,
                            border: `1px solid ${priority.border}`,
                            fontSize: 8,
                            fontWeight: 700,
                            whiteSpace: "nowrap",
                          }}
                        >
                          {item.priority}
                        </span>
                      </div>
                    );
                  },
                )}
              </div>
            </div>
          )}

          {explanation && (
            <div
              className="glass"
              style={{
                borderRadius: 8,
                padding: 18,
              }}
            >
              <div
                className="section-label"
                style={{
                  marginBottom: 14,
                }}
              >
                DECISION EXPLANATION
              </div>

              <div
                style={{
                  padding: 13,
                  borderRadius: 6,
                  background:
                    "rgba(0,200,232,0.035)",
                  border:
                    "1px solid rgba(0,200,232,0.12)",
                  marginBottom: 12,
                }}
              >
                <div
                  className="font-mono"
                  style={{
                    fontSize: 8,
                    color: "#00c8e8",
                    letterSpacing: "0.08em",
                    marginBottom: 5,
                  }}
                >
                  SUMMARY
                </div>

                <div
                  style={{
                    color: "#cbd5e1",
                    fontSize: 12,
                    lineHeight: 1.6,
                  }}
                >
                  {explanation.summary}
                </div>
              </div>

              <div
                style={{
                  display: "grid",
                  gridTemplateColumns:
                    "repeat(2, minmax(0, 1fr))",
                  gap: 10,
                }}
              >
                <ExplanationCard
                  title="DETAILED EXPLANATION"
                  text={
                    explanation.detailedExplanation
                  }
                />

                <ExplanationCard
                  title="OPERATIONAL IMPLICATION"
                  text={
                    explanation.operationalImplication
                  }
                />
              </div>

              <div
                style={{
                  marginTop: 12,
                }}
              >
                <div
                  className="font-mono"
                  style={{
                    fontSize: 8,
                    color: "#475569",
                    letterSpacing: "0.1em",
                    marginBottom: 8,
                  }}
                >
                  IMPACT FACTORS
                </div>

                <div
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    gap: 7,
                  }}
                >
                  {explanation.impactFactors.map(
                    (factor) => (
                      <span
                        key={factor}
                        style={{
                          padding:
                            "6px 9px",
                          borderRadius: 4,
                          background:
                            "rgba(148,163,184,0.04)",
                          border:
                            "1px solid rgba(148,163,184,0.1)",
                          color: "#94a3b8",
                          fontSize: 10,
                        }}
                      >
                        {factor}
                      </span>
                    ),
                  )}
                </div>
              </div>
            </div>
          )}

          {impact.length > 0 && (
            <div
              className="glass"
              style={{
                borderRadius: 8,
                padding: 18,
              }}
            >
              <div
                className="section-label"
                style={{
                  marginBottom: 12,
                }}
              >
                SIMULATION IMPACT INPUT
              </div>

              <div
                style={{
                  display: "grid",
                  gridTemplateColumns:
                    "repeat(auto-fit, minmax(150px, 1fr))",
                  gap: 8,
                }}
              >
                {impact.map((entry) => (
                  <div
                    key={entry.label}
                    style={{
                      padding: "9px 10px",
                      borderRadius: 5,
                      background:
                        "rgba(148,163,184,0.025)",
                      border:
                        "1px solid rgba(148,163,184,0.08)",
                    }}
                  >
                    <div
                      className="font-mono"
                      style={{
                        fontSize: 8,
                        color: "#475569",
                        marginBottom: 4,
                      }}
                    >
                      {entry.label}
                    </div>

                    <div
                      className="font-mono"
                      style={{
                        fontSize: 11,
                        color: "#94a3b8",
                        fontWeight: 600,
                      }}
                    >
                      {entry.value}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {simulation && (
            <div
              className="font-mono"
              style={{
                padding: "10px 12px",
                borderRadius: 5,
                background:
                  "rgba(148,163,184,0.025)",
                border:
                  "1px solid rgba(148,163,184,0.06)",
                color: "#475569",
                fontSize: 8,
              }}
            >
              BACKEND PIPELINE · {simulation.station} ·{" "}
              {simulation.scenarioName} ·{" "}
              {simulation.horizonHours}h ·{" "}
              {explanation?.recommendationCount ?? 0}{" "}
              recommendation(s)
            </div>
          )}
        </>
      )}
    </div>
  );
}

function MetricCard({
  label,
  value,
  valueColor = "#e2e8f0",
}: {
  label: string;
  value: string;
  valueColor?: string;
}) {
  return (
    <div
      className="glass"
      style={{
        borderRadius: 8,
        padding: 15,
      }}
    >
      <div
        className="font-mono"
        style={{
          fontSize: 8,
          color: "#475569",
          letterSpacing: "0.1em",
          marginBottom: 7,
        }}
      >
        {label}
      </div>

      <div
        className="font-display"
        style={{
          fontSize: 17,
          fontWeight: 700,
          color: valueColor,
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap",
        }}
      >
        {value}
      </div>
    </div>
  );
}

function ExplanationCard({
  title,
  text,
}: {
  title: string;
  text: string;
}) {
  return (
    <div
      style={{
        padding: 13,
        borderRadius: 6,
        background:
          "rgba(148,163,184,0.025)",
        border:
          "1px solid rgba(148,163,184,0.08)",
      }}
    >
      <div
        className="font-mono"
        style={{
          fontSize: 8,
          color: "#475569",
          letterSpacing: "0.08em",
          marginBottom: 6,
        }}
      >
        {title}
      </div>

      <div
        style={{
          color: "#94a3b8",
          fontSize: 11,
          lineHeight: 1.6,
        }}
      >
        {text}
      </div>
    </div>
  );
}